#!/bin/bash

# Custom signature generation script for Warkop X ECU
# This script overrides RusEFI's default signature to include timestamp

# Get board name from meta-info
BOARD_NAME="warkop_x"

# Use RUSEFI_BUILD_DATE from environment if available, otherwise generate locally
if [ -z "$RUSEFI_BUILD_DATE" ]; then
    # Format: YYYY-MM-DD_HH-MM (WIB timezone if TZ is set)
    SIGNATURE_DATE=$(date +'%Y.%m.%d_%H-%M')
else
    # Convert GitHub format YYYY-MM-DD_HH-MM to signature format YYYY.MM.DD_HH-MM
    SIGNATURE_DATE=$(echo "$RUSEFI_BUILD_DATE" | sed 's/-/./g' | sed 's/_\([0-9]\{2\}\)-\([0-9]\{2\}\)/_\1-\2/')
fi

# Get git branch (default to 'main' if not available)
BRANCH=${AUTOMATION_REF:-main}

# Create signature file
OUTPUT_FILE="generated/tunerstudio/generated/signature_${BOARD_NAME}.txt"

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Generate signature file
cat > "$OUTPUT_FILE" << EOF
! Generated by custom_signature_gen.sh
! SIGNATURE_HASH is a built-in variable generated by config_definition-all.jar
! Using custom timestamp format: ${SIGNATURE_DATE}
#define TS_SIGNATURE "rusEFI ${BRANCH}.${SIGNATURE_DATE}.${BOARD_NAME}.@@SIGNATURE_HASH@@"
EOF

echo "✅ Generated signature: rusEFI ${BRANCH}.${SIGNATURE_DATE}.${BOARD_NAME}.@@SIGNATURE_HASH@@"
echo "   Output: $OUTPUT_FILE"
