//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A10: return "PA10 (UART RX)";
		case Gpio::A15: return "PA15 (Digital)";
		case Gpio::A9: return "PA9 (UART TX)";
		case Gpio::B0: return "PB0 (Digital)";
		case Gpio::B10: return "PB10 (UART TX)";
		case Gpio::B11: return "PB11 (UART RX)";
		case Gpio::B13: return "PB13";
		case Gpio::B14: return "PB14";
		case Gpio::B15: return "PB15";
		case Gpio::B7: return "PB7";
		case Gpio::C10: return "PC10 (SD SCK)";
		case Gpio::C11: return "PC11 (SD MISO)";
		case Gpio::C12: return "PC12 (SD MOSI)";
		case Gpio::C7: return "PC7";
		case Gpio::C8: return "PC8";
		case Gpio::C9: return "PC9";
		case Gpio::D0: return "PD0 (CAN RX)";
		case Gpio::D1: return "PD1 (CAN TX)";
		case Gpio::D13: return "PD13";
		case Gpio::D2: return "PD2 (SD CS)";
		case Gpio::D3: return "PD3";
		case Gpio::D4: return "PD4";
		case Gpio::D7: return "PD7";
		case Gpio::D8: return "PD8";
		case Gpio::D9: return "PD9";
		case Gpio::E13: return "PE13";
		case Gpio::E14: return "PE14";
		case Gpio::E15: return "PE15";
		case Gpio::E5: return "PE5";
		case Gpio::E8: return "PE8";
		default: return nullptr;
	}
	return nullptr;
}
