//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::E15, // PE15
	Gpio::E14, // PE14
	Gpio::D13, // PD13
	Gpio::E5, // PE5
	Gpio::D8, // PD8
	Gpio::B15, // PB15
	Gpio::B14, // PB14
	Gpio::B13, // PB13
	Gpio::C8, // PC8
	Gpio::C7, // PC7
	Gpio::E8, // PE8
	Gpio::D9, // PD9
	Gpio::C9, // PC9
	Gpio::B7, // PB7
	Gpio::C12, // PC12 (SD MOSI)
	Gpio::C11, // PC11 (SD MISO)
	Gpio::C10, // PC10 (SD SCK)
	Gpio::D2, // PD2 (SD CS)
	Gpio::D1, // PD1 (CAN TX)
	Gpio::D0, // PD0 (CAN RX)
	Gpio::A9, // PA9 (UART TX)
	Gpio::A10, // PA10 (UART RX)
	Gpio::B10, // PB10 (UART TX)
	Gpio::B11, // PB11 (UART RX)
// "PE15",
// "PE14",
// "PD13",
// "PE5",
// "PD8",
// "PB15",
// "PB14",
// "PB13",
// "PC8",
// "PC7",
// "PE8",
// "PD9",
// "PC9",
// "PB7",
// "PC12 (SD MOSI)",
// "PC11 (SD MISO)",
// "PC10 (SD SCK)",
// "PD2 (SD CS)",
// "PD1 (CAN TX)",
// "PD0 (CAN RX)",
// "PA9 (UART TX)",
// "PA10 (UART RX)",
// "PB10 (UART TX)",
// "PB11 (UART RX)",
}
